#python run_any2.py  --section debug --model DINO --tag default
python run_any2.py --section bottle --model DINO --tag bottle --ontology "big crack : big crack, small crack : small crack, no defect : no defect"
python run_any2.py --section bottle --model Florence --tag bottle --ontology "big crack : big crack, small crack : small crack, no defect : no defect"
python run_any2.py --section defects --model DINO --tag defects --ontology "cracked rim: crack, blurred rim: blurred, contamination: contamination, anomaly: anomaly, spec: spec, a cat: cat, a dog: dog, smooth: smooth, damaged rim: damaged rim, sharp glass: sharp glass, missing piece: missing, dirty surface: dirty, chip on rim: chip, discoloration: discoloration, foreign particle: particle, residue: residue, broken section: broken, polished rim: polished, perfect condition: perfect, rough texture: rough, micro-cracks: micro-cracks, a bird: bird, a car: car, a flower: flower, a tree: tree, a glass bottle: glass bottle, intact rim: intact, visible flaw: flaw, small dent: dent, a plane: plane, an insect: insect"
python run_any2.py --section defects --model Florence --tag defects --ontology "cracked rim: crack, blurred rim: blurred, contamination: contamination, anomaly: anomaly, spec: spec, a cat: cat, a dog: dog, smooth: smooth, damaged rim: damaged rim, sharp glass: sharp glass, missing piece: missing, dirty surface: dirty, chip on rim: chip, discoloration: discoloration, foreign particle: particle, residue: residue, broken section: broken, polished rim: polished, perfect condition: perfect, rough texture: rough, micro-cracks: micro-cracks, a bird: bird, a car: car, a flower: flower, a tree: tree, a glass bottle: glass bottle, intact rim: intact, visible flaw: flaw, small dent: dent, a plane: plane, an insect: insect"
python run_any2.py --section wood --model DINO --tag wood --ontology "color: color, combined: combined, hole: hole, liquid: liquid, scratch: scratch"
python run_any2.py --section wood --model Florence --tag wood --ontology "color: color, combined: combined, hole: hole, liquid: liquid, scratch: scratch"
python run_any2.py --section wood --model DINO --tag wood --ontology "paint color: color, combined: combined, hole puncture missing: hole, liquid water droplet: liquid, scratch scratch mark line: scratch"


